### ISSUE TITLE
No validation error shown if activity validation fails

### ISSUE THREAD

**Issue by parkerabercrombie** [NASA-AMMOS/aerie#1116]
### Checked for duplicates

Yes - I've already checked

### Is this a regression?

No - This is a new bug

### Version

1.12.0

### Describe the bug

If the activity validation call fails the activity appears to be valid, and there is only a cryptic message in the error console to indicate something is wrong.

### Reproduction

Reproduces easily with the `SUDA_All_Characterization` activity in the Clipper model. Adding this activity with default arguments results in this error in the browser console:

```
Error: the key 'message' was not present
    at de (modal.19164a21.js:1773:11756)
    at async Object.validateActivityArguments (modal.19164a21.js:1773:65474)
    at async dl (ActivityDirectiveForm.dfc56627.js:8:87104)
```

### Logs

```shell
GraphQL request:

{
  "query": "#graphql\n    query ValidateActivityArguments($arguments: ActivityArguments!, $activityTypeName: String!, $modelId: ID!) {\n      validateActivityArguments(\n        activityArguments: $arguments,\n        activityTypeName: $activityTypeName,\n        missionModelId: $modelId\n      ) {\n        errors {\n          message\n          subjects\n        }\n        success\n      }\n    }\n  ",
  "variables": {
    "activityTypeName": "SUDA_All_Characterization",
    "arguments": {},
    "modelId": 1
  }
}
```

Response:
```
{
  "error": "unexpected response",
  "request": {
    "body": {
      "action": {
        "name": "validateActivityArguments"
      },
      "input": {
        "activityArguments": {},
        "activityTypeName": "SUDA_All_Characterization",
        "missionModelId": "1"
      },
      "request_query": "#graphql\n    query ValidateActivityArguments($arguments: ActivityArguments!, $activityTypeName: String!, $modelId: ID!) {\n      validateActivityArguments(\n        activityArguments: $arguments,\n        activityTypeName: $activityTypeName,\n        missionModelId: $modelId\n      ) {\n        errors {\n          message\n          subjects\n        }\n        success\n      }\n    }\n  ",
      "session_variables": {
        "x-hasura-role": "aerie_admin",
        "x-hasura-user-id": "abercrom"
      }
    },
    "headers": [],
    "transformed_request": null,
    "url": "{{AERIE_MERLIN_URL}}/validateActivityArguments"
  },
  "response": {
    "body": {
      "errors": [
        "Invalid arguments for input type \"SUDA_All_Characterization\": extraneous arguments: [], unconstructable arguments: [], missing arguments: [MissingArgument[parameterName=processDataVolume, schema=StructSchema[value={bytes=RealSchema[]}]], MissingArgument[parameterName=processDuration, schema=StructSchema[value={units=VariantSchema[variants=[Variant[key=MICROSECONDS, label=MICROSECONDS], Variant[key=MILLISECONDS, label=MILLISECONDS], Variant[key=SECONDS, label=SECONDS], Variant[key=MINUTES, label=MINUTES], Variant[key=HOURS, label=HOURS]]], quantity=IntSchema[]}]], MissingArgument[parameterName=scienceDur, schema=StructSchema[value={units=VariantSchema[variants=[Variant[key=MICROSECONDS, label=MICROSECONDS], Variant[key=MILLISECONDS, label=MILLISECONDS], Variant[key=SECONDS, label=SECONDS], Variant[key=MINUTES, label=MINUTES], Variant[key=HOURS, label=HOURS]]], quantity=IntSchema[]}]]], valid arguments: [ValidArgument[parameterName=endDuration, serializedValue=MapValue[map={units=StringValue[value=MINUTES], quantity=NumericValue[value=30]}]], ValidArgument[parameterName=estNumEvents, serializedValue=NumericValue[value=2000]], ValidArgument[parameterName=idleDuration, serializedValue=MapValue[map={units=StringValue[value=MINUTES], quantity=NumericValue[value=10]}]], ValidArgument[parameterName=mode, serializedValue=StringValue[value=SURVEY]], ValidArgument[parameterName=polarity, serializedValue=StringValue[value=POS]], ValidArgument[parameterName=quickbootDuration, serializedValue=MapValue[map={units=StringValue[value=SECONDS], quantity=NumericValue[value=45]}]], ValidArgument[parameterName=scienceConfig, serializedValue=StringValue[value=HSHG]], ValidArgument[parameterName=ScienceRecovery, serializedValue=BooleanValue[value=false]], ValidArgument[parameterName=seqBuffer, serializedValue=NumericValue[value=0]], ValidArgument[parameterName=seqEngine, serializedValue=StringValue[value=OPERATIONAL]], ValidArgument[parameterName=seqOffset, serializedValue=NumericValue[value=0]], ValidArgument[parameterName=setupDuration, serializedValue=MapValue[map={units=StringValue[value=MINUTES], quantity=NumericValue[value=2]}]], ValidArgument[parameterName=spawnPowerOff, serializedValue=BooleanValue[value=true]], ValidArgument[parameterName=spawnProcessing, serializedValue=BooleanValue[value=true]], ValidArgument[parameterName=sudaAID, serializedValue=NumericValue[value=-1897725952]], ValidArgument[parameterName=sudaShutDownDuration, serializedValue=MapValue[map={units=StringValue[value=MINUTES], quantity=NumericValue[value=1]}]]]"
      ],
      "success": false
    },
    "headers": [
      {
        "name": "Date",
        "value": "Tue, 29 Aug 2023 16:20:27 GMT"
      },
      {
        "name": "Content-Type",
        "value": "application/json"
      },
      {
        "name": "Content-Encoding",
        "value": "gzip"
      },
      {
        "name": "Content-Length",
        "value": "595"
      },
      {
        "name": "Server",
        "value": "Jetty(11.0.15)"
      }
    ],
    "status": 400
  }
}
```
```


### System Info

```shell
Chrome
```

### Severity

Moderate

**Comment by parkerabercrombie** [comment]
No errors in `merlin_server`. The error posted above does appear in the hasura log.

**Comment by camargo** [comment]
Possibly related https://github.com/NASA-AMMOS/aerie/issues/941

**Comment by camargo** [comment]
Seeing this in `merlin_server`:

```text
[qtp1843368112-66] INFO io.javalin.Javalin - JAVALIN REQUEST DEBUG LOG:
Request: POST [/validateActivityArguments]
    Matching endpoint-handlers: [BEFORE=*, BEFORE=*, POST=/validateActivityArguments, AFTER=*]
    Headers: {X-B3-SpanId=1b0bf5a748be31e4, X-B3-ParentSpanId=092ed7f68cd1fa02, User-Agent=hasura-graphql-engine/v2.12.1, Host=aerie_merlin:27183, X-B3-TraceId=238539f553bf76c2, Accept-Encoding=gzip, Content-Length=574, Content-Type=application/json}
    Cookies: {}
    Body: {"action":{"name":"validateActivityArguments"},"input":{"activityArguments":{},"activityTypeName":"SUDA_All_Characterization","missionModelId":"1"},"request_query":"query ValidateActivityArguments($arguments: ActivityArguments!, $activityTypeName: String!, $modelId: ID!) {\n  validateActivityArguments(\n    activityArguments: $arguments,\n    activityTypeName: $activityTypeName,\n    missionModelId: $modelId\n  ) {\n    errors {\n      message\n      subjects\n    }\n    success\n  }\n}","session_variables":{"x-hasura-role":"aerie_admin","x-hasura-user-id":"camargo"}}
    QueryString: null
    QueryParams: {}
    FormParams: {}
Response: [400 Bad Request], execution took 104.68 ms
    Headers: {Content-Encoding=gzip, Date=Tue, 29 Aug 2023 20:12:28 GMT, Content-Type=application/json}
    Body is gzipped (2916 bytes, not logged)
```

**Comment by camargo** [comment]
You can repro this with the Clipper model in the Hasura console:

```gql
query ValidateActivityArguments($arguments: ActivityArguments!, $activityTypeName: String!, $modelId: ID!) {
  validateActivityArguments(
    activityArguments: $arguments,
    activityTypeName: $activityTypeName,
    missionModelId: $modelId
  ) {
    errors {
      message
      subjects
    }
    success
  }
}
```

```json
{
  "arguments": {},
  "activityTypeName": "SUDA_All_Characterization",
  "modelId": 1 # Change to your model ID
}
```
