### ISSUE TITLE
Scheduling a goal again immediately after the previous one finishes results in error

### ISSUE THREAD

**Issue by duranb** [NASA-AMMOS/aerie#1165]
### Checked for duplicates

Yes - I've already checked

### Is this a regression?

No - This is a new bug

### Version

develop

### Describe the bug

The UI e2e test for scheduling the same goal twice has started to fail causing the PR checks to not pass. The PRs themselves don't have any scheduling related changes, so the suspicion is that scheduling changed in a way that makes the UI test obsolete.

We just need to know if there's a change that needs to be made to the tests.

### Reproduction

To reproduce:
1. Through the UI, create a Banananation plan
2. Then create the following scheduling goal and associate it to the plan created in step 1
```
export default (): Goal =>
    Goal.ActivityRecurrenceGoal({
        activityTemplate: ActivityTemplates.BakeBananaBread({
            temperature: 325.0,
            tbSugar: 2,
            glutenFree: false,
        }),
        interval: Temporal.Duration.from({ hours: 12 }),
    });
```
3. Navigate to the plan and open the scheduling panel
4. Click the `Schedule` button in the scheduling panel
5. Wait for the completion status
6. Click the `Schedule` button again
7. The error console should now have the following error:
```
java.lang.NullPointerException: Cannot read field "durationInMicroseconds" because "right" is null
	at gov.nasa.jpl.aerie.merlin.protocol.types.Duration.add(Duration.java:236)
	at gov.nasa.jpl.aerie.merlin.protocol.types.Duration.plus(Duration.java:361)
	at gov.nasa.jpl.aerie.scheduler.model.SchedulingActivityDirective.getEndTime(SchedulingActivityDirective.java:167)
	at gov.nasa.jpl.aerie.scheduler.solver.PrioritySolver.satisfyGoalGeneral(PrioritySolver.java:577)
	at gov.nasa.jpl.aerie.scheduler.solver.PrioritySolver.satisfyGoal(PrioritySolver.java:368)
	at gov.nasa.jpl.aerie.scheduler.solver.PrioritySolver.solve(PrioritySolver.java:325)
	at gov.nasa.jpl.aerie.scheduler.solver.PrioritySolver.getNextSolution(PrioritySolver.java:127)
	at gov.nasa.jpl.aerie.scheduler.worker.services.SynchronousSchedulerAgent.schedule(SynchronousSchedulerAgent.java:215)
	at gov.nasa.jpl.aerie.scheduler.worker.SchedulerWorkerAppDriver.main(SchedulerWorkerAppDriver.java:90)
```

### System Info

```shell
Chrome 117.0.5938.132, Mac OS 13.5.2 (22G91)
```

### Severity

Moderate

**Comment by mattdailis** [comment]
Consider porting the failing UI test to our e2e tests
