### ISSUE TITLE
Fix NASA Scrub in CI

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#535]
NASA Scrub scans are failing in CI. This issue is to fix it. [This PR](https://github.com/NASA-AMMOS/aerie/pull/534) is a temporary fix so we can keep moving with other PRs.

```
Run python3 -m pip install nasa-scrub
Defaulting to user installation because normal site-packages is not writeable
Collecting nasa-scrub
  Downloading nasa_scrub-2.6.1-py2.py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB 1.8 MB/s eta 0:00:00
Installing collected packages: nasa-scrub
Successfully installed nasa-scrub-2.6.1
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/scrub/scrub/scrub/tools/parsers/csv_parser.py", line 66, in <module>
    parse_warnings(pathlib.Path(sys.argv[1]).resolve())
  File "/home/runner/work/scrub/scrub/scrub/tools/parsers/csv_parser.py", line 57, in parse_warnings
    result.get('file').relative_to(source_dir),
  File "/usr/lib/python3.10/pathlib.py", line 818, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/home/runner/work/scrub/scrub/scrub/targets/collaborator/do_collaborator.py' is not in the subpath of '/home/runner/work/scrub/results' OR one path is relative and the other is absolute.
Error: Process completed with exit code 1.
```

**Comment by camargo** [comment]
The NASA Scrub repo itself also seems to be failing in GitHub Actions right now with the same type of error: https://github.com/nasa/scrub/actions/runs/3673227034/jobs/6210119677
