### ISSUE TITLE
IllegalStateException while simulating plan

### ISSUE THREAD

**Issue by parkerabercrombie** [NASA-AMMOS/aerie#614]
I've seen this database error a couple times while simulating. Both times it was preceeded by a _ton_ of "transaction in progess" warnings. The simulation succeeded when I tried again.

```
postgres            | 2023-01-23 19:48:42.430 UTC [541] WARNING:  there is already a transaction in progress
postgres            | 2023-01-23 19:48:42.431 UTC [541] WARNING:  there is already a transaction in progress
merlin_worker_1     | java.lang.IllegalStateException: Unhandled message: 2 @ com.impossibl.postgres.protocol.v30.PrepareRequest$Handler
merlin_worker_1     | 	at com.impossibl.postgres.protocol.v30.MessageDispatchHandler.dispatch(MessageDispatchHandler.java:225)
merlin_worker_1     | 	at com.impossibl.postgres.protocol.v30.MessageDispatchHandler.channelRead(MessageDispatchHandler.java:152)
merlin_worker_1     | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
merlin_worker_1     | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
merlin_worker_1     | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
merlin_worker_1     | 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
merlin_worker_1     | 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
merlin_worker_1     | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
merlin_worker_1     | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
merlin_worker_1     | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
merlin_worker_1     | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
merlin_worker_1     | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
merlin_worker_1     | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
merlin_worker_1     | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
merlin_worker_1     | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
merlin_worker_1     | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
merlin_worker_1     | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
merlin_worker_1     | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
merlin_worker_1     | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
merlin_worker_1     | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
merlin_worker_1     | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
merlin_worker_1     | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
merlin_worker_1     | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
merlin_worker_1     | 	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by parkerabercrombie** [comment]
I only had one simulation worker running when I saw this error.

**Comment by parkerabercrombie** [comment]
The error occurred with the attached plan. I had set the `errorHandling` to `EXCEPTION` in the simulation config, but otherwise was using default values.

[invalidstateexception-plan.json.txt](https://github.com/NASA-AMMOS/aerie/files/10483929/invalidstateexception-plan.json.txt)

**Comment by colin-lewis-19** [comment]
I have been experiencing this issue often. I can consistently trigger it by running a sequence of simulations through eurc's graph_connect.py script. Which plan/simulation from the script that causes the error is inconsistent between runs, however. That script is part of eurc's CI pipeline, so this issue is beginning to interfere with our PR workflow.

**Comment by sschaffe** [comment]
Adding that I am seeing this intermittently on aerie 1.1.0 as well.

**Comment by parkerabercrombie** [comment]
We're hitting this a _lot_ on our CI server.

**Comment by parkerabercrombie** [comment]
FWIW we're still seeing this in Aerie 1.2.0

**Comment by camargo** [comment]
Some discussion on this https://jpl.slack.com/archives/CJ07FGRPH/p1679958819954159
There may be an issue with the Postgres driver we are using: https://github.com/impossibl/pgjdbc-ng/issues/495
Per @mattdailis we need to do a trade to see about switching to https://jdbc.postgresql.org/, if the driver is indeed the issue.

Trade study ticket: https://github.com/NASA-AMMOS/aerie/issues/819

**Comment by parkerabercrombie** [comment]
FWIW still happening w/ Aerie 1.4.0

**Comment by camargo** [comment]
@parkerabercrombie, @mattdailis has been investigating and https://github.com/NASA-AMMOS/aerie/pull/833 _may_ fix this. Still testing. Stay tuned.

**Comment by parkerabercrombie** [comment]
Still occurs in 1.7.0 :(
