### ISSUE TITLE
Cannot read field "durationInMicroseconds" because "right" is null

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#633]
Running a scheduling goal twice in a row for Banananation on develop gives the error:

```text
java.lang.NullPointerException: Cannot read field "durationInMicroseconds" because "right" is null
	at gov.nasa.jpl.aerie.merlin.protocol.types.Duration.add(Duration.java:230)
	at gov.nasa.jpl.aerie.merlin.protocol.types.Duration.plus(Duration.java:355)
	at gov.nasa.jpl.aerie.scheduler.model.ActivityInstance.getEndTime(ActivityInstance.java:127)
	at gov.nasa.jpl.aerie.scheduler.solver.PrioritySolver.satisfyGoalGeneral(PrioritySolver.java:506)
	at gov.nasa.jpl.aerie.scheduler.solver.PrioritySolver.satisfyGoal(PrioritySolver.java:332)
	at gov.nasa.jpl.aerie.scheduler.solver.PrioritySolver.solve(PrioritySolver.java:291)
	at gov.nasa.jpl.aerie.scheduler.solver.PrioritySolver.getNextSolution(PrioritySolver.java:127)
	at gov.nasa.jpl.aerie.scheduler.worker.services.SynchronousSchedulerAgent.schedule(SynchronousSchedulerAgent.java:198)
	at gov.nasa.jpl.aerie.scheduler.worker.SchedulerWorkerAppDriver.main(SchedulerWorkerAppDriver.java:91)
```

Here is the goal: 

```ts
export default (): Goal =>
  Goal.ActivityRecurrenceGoal({
    activityTemplate: ActivityTemplates.BakeBananaBread({ temperature: 325.0, tbSugar: 2, glutenFree: false }),
    interval: Temporal.Duration.from({ hours: 12 }),
  });
```

This is causing the UI e2e tests to fail in PR.

**Comment by adrienmaillard** [comment]
Replicated the issue via test in the backend.
