### ISSUE TITLE
Aerie got stuck at the login page when we turned on "CAM" authentication with JWT disabled

### ISSUE THREAD

**Issue by parkerabercrombie** [NASA-AMMOS/aerie#958]
### Checked for duplicates

Yes - I've already checked

### Is this a regression?

No - This is a new bug

### Version

1.7.0

### Describe the bug

Unable to login to Aerie when JWT authentication is disabled.

### Reproduction

Not sure if this is something Aeire support, but we tried to turn off JWT authentication by commenting out all the "SECRET" environment variables in the docker-compose file.

When we tried to deploy Aeire with the "CAM" authentication, Aerie got stuck on the login page, and there were errors from the gateway log(see below);

On the other hand, it works if we set Aerie authentication to "none." However, we will still see a login page asking for a username and password.

### Logs

```shell
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at generateJwt (file:///app/dist/packages/auth/functions.js:37:36)
    at login (file:///app/dist/packages/auth/functions.js:81:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///app/dist/packages/auth/routes.js:42:26
Error: Authorization header does not include 'Bearer' prefix
    at authorizationHeaderToToken (file:///app/dist/packages/auth/functions.js:13:19)
    at decodeJwt (file:///app/dist/packages/auth/functions.js:22:23)
    at session (file:///app/dist/packages/auth/functions.js:147:32)
    at file:///app/dist/packages/auth/routes.js:82:32
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
Error: Authorization header does not include 'Bearer' prefix
    at authorizationHeaderToToken (file:///app/dist/packages/auth/functions.js:13:19)
    at decodeJwt (file:///app/dist/packages/auth/functions.js:22:23)
    at session (file:///app/dist/packages/auth/functions.js:147:32)
    at file:///app/dist/packages/auth/routes.js:82:32
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
Error: Authorization header does not include 'Bearer' prefix
    at authorizationHeaderToToken (file:///app/dist/packages/auth/functions.js:13:19)
    at decodeJwt (file:///app/dist/packages/auth/functions.js:22:23)
    at session (file:///app/dist/packages/auth/functions.js:147:32)
    at file:///app/dist/packages/auth/routes.js:82:32
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
```

### System Info

```shell
Mac OS, Chrome
```

### Severity

Moderate

**Comment by parkerabercrombie** [comment]
We were trying to run with JWT disabled to see if we could use 1.7.0 for our upcoming thread test (we don't have enough time to update our other tooling to support JWT auth before the test). We do not have a long term need to disable JWT auth. We can also use 1.6.0 for the thread test; we were considering 1.7.0 just to get the latest-and-greatest UI updates in front of our users.
