### ISSUE TITLE
Scheduling hangs due to duplicate scheduling specification ID

### ISSUE THREAD

**Issue by parkerabercrombie** [NASA-AMMOS/aerie#971]
### Checked for duplicates

Yes - I've already checked

### Is this a regression?

Yes - This worked in a previous version

### Version

1.6.0

### Describe the bug

When running scheduling our database got into a state where scheduling would fail with this error in the scheduler_worker log:
```
Exception in thread "main" java.lang.Error: Claiming a scheduling request for specification id 100 returned more than one result row.
```

### Reproduction

Not sure yet how to reproduce. We are rebuilding the database to try again.

### Logs

```shell
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
com.impossibl.postgres.jdbc.PGSQLSimpleException: Connection Error: Connection refused: postgres/172.20.0.2:5432
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:138)
	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:326)
	at com.impossibl.postgres.jdbc.AbstractDataSource.createConnection(AbstractDataSource.java:125)
	at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:71)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at gov.nasa.jpl.aerie.scheduler.worker.SchedulerWorkerAppDriver.main(SchedulerWorkerAppDriver.java:58)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: postgres/172.20.0.2:5432
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "main" com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Connection Error: Connection refused: postgres/172.20.0.2:5432
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at gov.nasa.jpl.aerie.scheduler.worker.SchedulerWorkerAppDriver.main(SchedulerWorkerAppDriver.java:58)
Caused by: com.impossibl.postgres.jdbc.PGSQLSimpleException: Connection Error: Connection refused: postgres/172.20.0.2:5432
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:138)
	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:326)
	at com.impossibl.postgres.jdbc.AbstractDataSource.createConnection(AbstractDataSource.java:125)
	at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:71)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 3 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: postgres/172.20.0.2:5432
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Unknown Source)
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[main] INFO com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection com.impossibl.postgres.jdbc.PGDirectConnection@5876a9af
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
[main] INFO io.javalin.Javalin - Starting Javalin ...
[main] INFO org.eclipse.jetty.server.Server - jetty-11.0.12; built: 2022-09-14T02:38:00.723Z; git: d5b8c29485f5f56a14be5f20c2ccce81b93c5555; jvm 19.0.2+7
[main] INFO org.eclipse.jetty.server.session.DefaultSessionIdManager - Session workerName=node0
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started i.j.j.@4d18aa28{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@71529963{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
[main] INFO org.eclipse.jetty.server.Server - Started Server@1e636ea3{STARTING}[11.0.12,sto=0] @1614ms
[main] INFO io.javalin.Javalin -
       __                  ___          ______
      / /___ __   ______ _/ (_)___     / ____/
 __  / / __ `/ | / / __ `/ / / __ \   /___ \
/ /_/ / /_/ /| |/ / /_/ / / / / / /  ____/ /
\____/\__,_/ |___/\__,_/_/_/_/ /_/  /_____/

       https://javalin.io/documentation

[main] INFO io.javalin.Javalin - Listening on http://localhost:8080/
[main] INFO io.javalin.Javalin - You are running Javalin 5.1.2 (released October 24, 2022. Your Javalin version is 226 days old. Consider checking for a newer version.).
[main] INFO io.javalin.Javalin - Javalin started in 253ms \o/
[PG-JDBC I/O (1)] INFO gov.nasa.jpl.aerie.scheduler.worker.ListenSchedulerCapability - Received PSQL Notification: 470, scheduling_request_notification, {"specification_revision":33,"specification_id":100,"analysis_id":29}
Exception in thread "main" java.lang.Error: Claiming a scheduling request for specification id 100 returned more than one result row.
	at gov.nasa.jpl.aerie.scheduler.server.remotes.postgres.PostgresResultsCellRepository.claim(PostgresResultsCellRepository.java:77)
	at gov.nasa.jpl.aerie.scheduler.worker.SchedulerWorkerAppDriver.main(SchedulerWorkerAppDriver.java:85)
[PG-JDBC I/O (1)] INFO gov.nasa.jpl.aerie.scheduler.worker.ListenSchedulerCapability - Received PSQL Notification: 470, scheduling_request_notification, {"specification_revision":4,"specification_id":108,"analysis_id":30}
[PG-JDBC I/O (1)] INFO gov.nasa.jpl.aerie.scheduler.worker.ListenSchedulerCapability - Received PSQL Notification: 691, scheduling_request_notification, {"specification_revision":5,"specification_id":108,"analysis_id":31}
```

### System Info

```shell
Chrome, MacOS
```

### Severity

Moderate

**Comment by adrienmaillard** [comment]
I have seen the same happening when attaching a debugger for too long : https://jpl.slack.com/archives/CJ07FGRPH/p1685147826066289

**Comment by duranb** [comment]
Just to have it documented here, after briefly looking with @Mythicaeda at this, it looks like the UI is polling the `schedule` function to get a `status`. If that `status` is not "complete" or "failed", it will keep polling every 500 ms until those conditions are met.

**Comment by mattdailis** [comment]
> Just to have it documented here, after briefly looking with @Mythicaeda at this, it looks like the UI is polling the `schedule` function to get a `status`. If that `status` is not "complete" or "failed", it will keep polling every 500 ms until those conditions are met.

That is accurate :+1: This should not result in a new request unless the scheduling specification's `revision` has changed in the interrim.

Here is the "claim" logic - looks like if there are multiple pending requests for the same `specification_id`, this query will return multiple rows:
https://github.com/NASA-AMMOS/aerie/blob/2a3b67cae5a333d83f3c1d52895fd170f9ff71dd/scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/remotes/postgres/ClaimRequestAction.java#L10-L13

A happy path is:
1. Issue scheduling request 1
2. Scheduling worker claims request 1
3. Modify scheduling specification
4. Issue scheduling request 2
5. Scheduling worker claims request 2

(Steps 2 and 3 can switch places without triggering this bug)

The sad path is:
1. Issue scheduling request 1
2. Modify scheduling specification
3. Issue scheduling request 2
4. Scheduling worker tries to claim both requests and gets confused

The `simulate` action, which works similarly, doesn't have the same vulnerability; the simulation worker's query filters by `dataset_id`, which can return at most one row, because the dataset_id is constrained to be unique:
https://github.com/NASA-AMMOS/aerie/blob/2a3b67cae5a333d83f3c1d52895fd170f9ff71dd/merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/ClaimSimulationAction.java#L11-L14

**Comment by Mythicaeda** [comment]
> That is accurate 👍 This should not result in a new request unless the scheduling specification's revision has changed in the interrim.

I took another look into this, and it looks like every time a scheduling request is made, the spec's revision is incremented for some reason.

**Comment by camargo** [comment]
> I took another look into this, and it looks like every time a scheduling request is made, the spec's revision is incremented for some reason.

When scheduling from the UI we [first update](https://github.com/NASA-AMMOS/aerie-ui/blob/3b80ee065a4aff4f5d990e56ab6472d9ec371970/src/utilities/effects.ts#L2638-L2640) the specs `plan_revision`, which I'm assuming is causing the `revision` field to increment?

**Comment by Mythicaeda** [comment]
> When scheduling from the UI we [first update](https://github.com/NASA-AMMOS/aerie-ui/blob/3b80ee065a4aff4f5d990e56ab6472d9ec371970/src/utilities/effects.ts#L2638-L2640) the specs plan_revision, which I'm assuming is causing the revision field to increment?

Yeah, exactly, via [this trigger](https://github.com/NASA-AMMOS/aerie/blob/develop/scheduler-server/sql/scheduler/tables/scheduling_specification.sql#L55-L59)

**Comment by Mythicaeda** [comment]
Regarding the `plan_revision` column on the scheduling spec table: what's the purpose of this column? I understand why it's useful on the scheduling rq table, but the spec's revision history is unrelated to the plan's revision history.

**Comment by camargo** [comment]
> what's the purpose of this column? 

AFAIK it exists to tell the scheduler what plan revision to schedule to (that's how we use it on the front-end at least).

**Comment by camargo** [comment]
Just noting that I verified smashing on the schedule button in the UI easily reproduces this error.

**Comment by Mythicaeda** [comment]
> AFAIK it exists to tell the scheduler what plan revision to schedule to (that's how we use it on the front-end at least).

By this do you mean it's used to fill in the `plan_revision` column on the requests table or something else? If it's the former, then maybe we should have the `schedule` action fetch that data rather than having the UI/API users maintain it on the spec table, [especially since there's already code in the scheduler server to fetch the revision data](https://github.com/NASA-AMMOS/aerie/blob/develop/scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/GraphQLMerlinService.java#L175-L191).

**Comment by camargo** [comment]
> By this do you mean it's used to fill in the `plan_revision` column on the requests table or something else? 

I don't see a `plan_revision` on the `scheduling_request` table, are we talking about the same thing?

**Comment by Mythicaeda** [comment]
> I don't see a `plan_revision` on the `scheduling_request` table, are we talking about the same thing?

Huh, you're right, must've been thinking of `sim_dataset`. Why _isn't_ `plan_revision` on `scheduling_request`?

**Comment by camargo** [comment]
> Why isn't plan_revision on scheduling_request?

Historically the "scheduling specification" has been used as input to the scheduler to associate scheduling configuration with plans, where the "scheduling request" is more like an output record. It made more sense when we also had a "scheduling template" to associate scheduling configuration with models, but we descoped that.

Elaborating on the history a bit. @mattdailis Brought up the scheduling request did not exist initially (it was added when we added scheduling workers), so in the original implementation of the spec it made sense to include the plan revision. Now that we have the request it makes more sense to include the plan revision there so we can more easily uniquely target scheduling requests in the worker.

**Comment by mattdailis** [comment]
We discussed this briefly in a huddle, and agreed on the following path forward:
1. We will refactor the scheduler's tables' schema by moving the `plan_revision` column from `scheduling_specification` to `scheduling_request`. It will become part of the unique key on `scheduling_specification`
2. We will implement an auto-cancel trigger, when a new scheduling request comes in, it will cancel the previous scheduling request for the same specification, provided that the plan_revision is different
